services:
  # Conteneur PHP avec FPM (FastCGI)
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - logs_volume:/var/www/html/logs
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # Monte la config Xdebug
    networks:
      - appnet

  # Conteneur Nginx pour servir l'app PHP
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - appnet

  # Base de données MariaDB 10.11
  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vehicles_consumptions_datas
      MYSQL_USER: jam_diff
      MYSQL_PASSWORD: jamDiff123#
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

volumes:
  dbdata:
  logs_volume:

networks:
  appnet: