CREATE TABLE IF NOT EXISTS brand
(
    id          INT AUTO_INCREMENT PRIMARY KEY,
    brand_name        VARCHAR(255) NOT NULL UNIQUE,
    nationality ENUM ('JP', 'DE', 'US', 'CN', 'KR', 'FR', 'IT', 'GB', 'ES', 'CA', 'IN', 'MX', 'TH', 'BR', 'SW', 'SK', 'RU'),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT IGNORE INTO brand (brand_name, nationality)
VALUES ('ALFA ROMEO', 'IT'),
       ('ASTON MARTIN', 'GB'),
       ('AUDI', 'DE'),
       ('BENTLEY', 'GB'),
       ('BMW', 'DE'),
       ('CHEVROLET', 'US'),
       ('CHRYSLER', 'US'),
       ('CITROEN', 'FR'),
       ('DACIA', 'FR'),
       ('DAIHATSU', 'JP'),
       ('DANGEL', 'FR'),
       ('DODGE', 'US'),
       ('FERRARI', 'IT'),
       ('FIAT', 'IT'),
       ('FORD', 'US'),
       ('HONDA', 'JP'),
       ('HYUNDAI', 'KR'),
       ('INFINITI', 'JP'),
       ('JAGUAR', 'GB'),
       ('JEEP', 'US'),
       ('KIA', 'KR'),
       ('LADA', 'RU'),
       ('LAMBORGHINI', 'IT'),
       ('LANCIA', 'IT'),
       ('LAND ROVER', 'GB'),
       ('LEXUS', 'JP'),
       ('LTI VEHICLES', 'GB'),
       ('MERCEDES-BENZ', 'DE'),
       ('MERCEDES-AMG', 'DE'),
       ('MINI', 'GB'),
       ('MITSUBISHI', 'JP'),
       ('NISSAN', 'JP'),
       ('OPEL', 'DE'),
       ('PEUGEOT', 'FR'),
       ('PGO', 'FR'),
       ('PORSCHE', 'DE'),
       ('RENAULT', 'FR'),
       ('SAAB', 'SW'),
       ('SEAT', 'ES'),
       ('SKODA', 'SK'),
       ('SMART', 'DE'),
       ('SSANGYONG', 'KR'),
       ('SUBARU', 'JP'),
       ('SUZUKI', 'JP'),
       ('TOYOTA', 'JP'),
       ('VOLKSWAGEN', 'DE'),
       ('VOLVO', 'SW')
